### ISSUE TITLE
Trying to replicate the work

### ISSUE THREAD

**Issue by dayuyang1999** [AI4Finance-Foundation/FinGPT#11]
Hi Authors,

Thanks to open-source this great work.

I am wondering:
1. if the FinGPT refered in [the finGPT paper](https://arxiv.org/abs/2306.06031) V1 or V2? I guess it is V2 but under v2 I only found a simple script for downloading some data.
2. it seems that I didn't see the "stock return RL" step on the script. And there is no evaluation metric shown in the paper. Is there any quantitative evidence shows Stock return RL improve performance on some tasks?
3. It seems there is no instruction on README showing how to replicate the work from 0 to 1 that is demonstrated on the [FinGPT website demo](https://ai4finance-foundation.github.io/FinNLP/)

Could you please provide some information about these?

Thanks,

**Comment by EricaSilas** [comment]
Thanks,

**Comment by yinjianjie** [comment]
how to get data?

**Comment by oliverwang15** [comment]
Hi dayuyang1999:

1. We will open-source the code of V2 in a few days, and since the differences between v1 and v2 are mainly on the data sources and the base model, you may refer to the codes in v1 first.

2. "Stock return RL", which is called "Fine-tuning via Reinforcement Learning on Stock Prices (RLSP)", is actually an idea proposed by our team which was inspired by Reinforcement Learning on Human Feedback (RLHF), as utilized by ChatGPT. Our team will finish the experiments soon and will post the results as soon as possible.

3. Good Suggestion! We will soon post our hands-on tutorial on the FinGPT website.

**Comment by oliverwang15** [comment]
Hi, yinjianjie. We have another repo named "[FinNLP](https://github.com/AI4Finance-Foundation/FinNLP)" which mainly focuses on the test data in the field of finance. You may check that repo for more information about data,
